name: Build and Save APK

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_KEY_TODO: ${{ secrets.API_KEY_TODO }}
      API_KEY_FIREBASE_ANDROID: ${{ secrets.API_KEY_FIREBASE_ANDROID }}
      API_KEY_FIREBASE_IOS: ${{ secrets.API_KEY_FIREBASE_IOS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0

      - name: Install dependencies
        run: flutter pub get

      #    - name: Statically analyze the Dart code for any errors.
      #      run: flutter analyze .

      #name: Run widget tests for our flutter project.
      #- run: flutter test

      - name: Build Android Release
        run: flutter build apk --release --dart-define=API_KEY_TODO=${{ secrets.API_KEY_TODO }} --dart-define=API_KEY_FIREBASE_ANDROID=${{ secrets.API_KEY_FIREBASE_ANDROID }} --dart-define=API_KEY_FIREBASE_IOS=${{ secrets.API_KEY_FIREBASE_IOS }}


      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
